name: Hello

on: [push]

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print Hello World
      run: echo "Hello World!"

    - name: Print Date
      run: date

    - name: List Directory Contents
      run: ls -l
